name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        # os: [ubuntu-latest, macos-14]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          # CIBW_ENVIRONMENT: |
          #   CBLAS_DIR="${{ env.CBLAS_DIR }}"
          #   CFLAGS="${{ env.CFLAGS }}"
          #   LDFLAGS="${{ env.LDFLAGS }}"
          MACOSX_DEPLOYMENT_TARGET: "14.0"
        with:
          package-dir: .
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl